import type { Metadata } from "next";
import { Big_Shoulders, Schibsted_Grotesk, Geist_Mono } from "next/font/google";
import GrainOverlay from "@/components/shared/GrainOverlay";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";
import "./globals.css";
// No fallback metrics exist for the consolidated Big Shoulders, so the adjusted
// fallback can't be generated; opt out to keep the build warning-free.
const bigShoulders = Big_Shoulders({
  subsets: ["latin"],
  axes: ["opsz"],
  display: "swap",
  variable: "--font-display",
  adjustFontFallback: false,
  fallback: ["sans-serif"],
});
const schibstedGrotesk = Schibsted_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});
const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bigShoulders.variable} ${schibstedGrotesk.variable} ${geistMono.variable}`}
    >
      <body className="antialiased">
        <GrainOverlay />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}